### PR TITLE
added osx wallpaper finding

### LINKED ISSUE #16: Blank Output on OSX
Like literally nothing. 

It just gets stuck like this:

 this

No output in regular terminal.app or iterm, when run from bash or fish. This is on OSX beta, but I doubt that would make a difference.

### PR DESCRIPTION
**Pull request by Goerofmuns**
this fixes a bug where on OSX the script couldn't find wallpaper.

fixes #16

### CODE REVIEW

**Comment by dylanaraps** [comment]
Thanks for the pull request!

It'd be better if we moved the wallsource variable to the wallpaper function itself. We can also use variable substitution instead of sed as it's faster since we're not spawning any externel processes.

What does this command below output? 

```sh
osascript -e 'tell app "finder" to get posix path of (get desktop picture as text)')
```

**Comment by Goerofmuns** [comment]
That does give the correct output, a path to my wallpaper. I can update the fork and PR, or you can just do it yourself.

Also looking back at the commit I see what you mean, this is why I shouldn't multitask. :)

**Comment by dylanaraps** [comment]
Awesome! 

I'll add it myself. One more quick question, what does the output look like? I want to see whether or not we'll need to quote the path.

Thanks again for the pr!

**Comment by dylanaraps** [comment]
I've pushed it to master, let me know if it works or not.

**Comment by Goerofmuns** [comment]
Just remove the double quote escaping backslashes in `\"Finder\"` so its `"Finder"`. osascript doesn't seem to like them.

**Comment by dylanaraps** [comment]
Wait a sec.

**Comment by dylanaraps** [comment]
I'm trying to quote the path but the command already uses both types of quotes. Are you able to paste the exact output from the command? I want to see whether or not the path output escapes spaces etc.

**Comment by Goerofmuns** [comment]
>9:10: syntax error: Expected expression, property or key form, etc. but found unknown token. (-2741)

That's what `osascript` gives when I run fetch.

`osascript -e 'tell app "finder" to get posix path of (get desktop picture as text)'` this runs fine but like you said it's that extra pair of quotes.

**Comment by dylanaraps** [comment]
Are you able to give me the output of the working command?

**Comment by Goerofmuns** [comment]
`/Users/tom/wall/vla.jpg` aka my wallpaper path.

**Comment by dylanaraps** [comment]
I've removed the quotes and pushed it to master, it should work now. I'm not sure about what will happen if the path has spaces in it though.

Thanks for the PR!

**Comment by Goerofmuns** [comment]
All works well! Nice work.

**Comment by dylanaraps** [comment]
I just pushed another commit, try it out again please!

**Comment by Goerofmuns** [comment]
still works!

**Comment by dylanaraps** [comment]
Awesome!

Thanks for all the help!

**Pull request closed without merging**
