### PR TITLE
Image size multiplier.

### PR DESCRIPTION
**Pull request by Wyn10**
After halving the image I still have plenty of room to work with.  Added a multiply so I can increase the base image size before halving without wrecking the final size.

### CODE REVIEW

**Comment by dylanaraps** [comment]
I don't quite understand what this new feature does or why we need it, care to elaborate?

**Comment by Wyn10** [comment]
After halving the image to fit into the console I still have room for the image to be bigger without squishing the text.  So I added a multiplier so I can make the image bigger and use the extra space.

**Comment by dylanaraps** [comment]
I still don't understand what you mean by "bigger", can you show me an example of with/without the setting enabled?

**Comment by Wyn10** [comment]
Sure.  I'm better at pictures.

This is with image size multiplier at 0, so half the terminal width as normal:

Alt text

This is with image size multiplier at 300, the image is still half to fit the console:

Alt text

The image gets bigger to fill the unneeded space.  Sorry for the bad explanation.

**Comment by dylanaraps** [comment]
I think I understand now.

It's a good idea, I just think it should be implemented differently. What I've done
in a seperate branch called `size` is make the launch flag `--size` also take a
percentage as a value.

For example:

```sh
# Image takes up 70% of terminal size
fetch --size 70%

# Image takes up 20% of terminal size
fetch --size 20%
```

This way it scales with the window size and also works on smaller terminal sizes.
This also takes terminal height into account when the image won't fit the window
size.

**Comment by Wyn10** [comment]
Perfect :grinning:.  I am using 53% which does the same as I was doing.

Sorry again for the bad explanation.

**Comment by dylanaraps** [comment]
All good! 

Thanks for the original PR. :)

**Pull request closed without merging**
