### PR TITLE
Implementation for battery level, working with multiple batteries

### PR DESCRIPTION
**Pull request by tudurom**

### CODE REVIEW

**Comment by tudurom** [comment]
Working on a multi battery one.

**Comment by tudurom** [comment]
```
^
|
```

**Comment by dylanaraps** [comment]
I'm already working on it locally and I'm almost done!

**Comment by tudurom** [comment]
A multi line one?

**Comment by dylanaraps** [comment]
Yup!

**Comment by dylanaraps** [comment]
I'm not sure if the battery path is correct as I'm working with dummy files
on my pc. This prints each battery on a seperate line and numbers the title
accordingly.

Here's what I've got so far, test it out!:

```sh
getbattery () {
    case "$os" in
        "Linux")
            batteries=($(cat /sys/class/power_supply/BAT*/capacity))

            # If there's only a single battery,
            # don't number the subtitle.
            if [ "${#batteries[@]}" == 1 ]; then
                prin "Battery: ${batteries[0]}%"
                return
            fi

            # Print each battery on a seperate line.
            index=1
            for bat in ${batteries[@]}; do
                prin "Battery${index}: ${bat}%"
                index=$((index + 1))
            done
        ;;
    esac
}
```

**Comment by tudurom** [comment]
The "Battery" text should be styled as in the config file.

**Comment by tudurom** [comment]
Yeah, the path seems correct. I have done my implementation on a laptop.

**Comment by dylanaraps** [comment]
Yup!

I'm working on letting the user style it the same as the other titles.

**Comment by tudurom** [comment]
Btw on some models the first battery is `BAT0` while on others it's called `BAT1`, but I don't think it makes a difference.

**Comment by dylanaraps** [comment]
It doesn't make a difference with the way I've set it up!

**Comment by dylanaraps** [comment]
Also changing the title for the batteries works now.

**Comment by kelaun** [comment]
If the first battery is 0 and there are multiple batteries, should the index not be 0 instead of 1 at the starting point?

**Comment by tudurom** [comment]
I have 1 battery and it's called 0. No problem.

**Comment by dylanaraps** [comment]
I'll change the index to `0`, you're right.

**Comment by tudurom** [comment]
I realised I just said a very dumb thing.

**Comment by kelaun** [comment]
Shouldn't you first check if BAT0 exists? Otherwise the index should indeed be 1.

**Comment by dylanaraps** [comment]
Yup, the function has no error handlng at the moment.

**Comment by dylanaraps** [comment]
It's in master now, please test it out.

**Comment by dylanaraps** [comment]
I'm closing this PR, lets move discussion to **#30**.

**Comment by tudurom** [comment]
Works.

**Comment by dylanaraps** [comment]
Awesome!

Thanks for your PR too!

**Comment by tudurom** [comment]
No problem.

**Pull request closed without merging**
