### PR TITLE
Changed image cache location

### PR DESCRIPTION
**Pull request by tudurom**
I made something!

### CODE REVIEW

**Comment by tudurom** [comment]
Shit, typo

**Comment by dylanaraps** [comment]
Yup! :)

**Comment by tudurom** [comment]
Well, fetch is kinda the most important open-source project I contributed, so, what do I do, submit a new pull request or I reference a new commit and it is included in the pull request by magic?

**Comment by tudurom** [comment]
Ah, GitHub made it by itself!

**Comment by dylanaraps** [comment]
Thanks!

**Comment by tudurom** [comment]
Thank you too for helping me learn this thing!

**Pull request merged**
