### PR TITLE
Battery support for OpenBSD

### PR DESCRIPTION
**Pull request by tudurom**

### CODE REVIEW

**Comment by dylanaraps** [comment]
What does the output look like?

Also your indenting is wrong again, you've got `5` spaces instead of `4`.

**Comment by tudurom** [comment]
My vim indents with 2 spaces because that's how I like it. On fetch I
indent manually. The output looks like `97%`.

**Comment by dylanaraps** [comment]
I'll add a comment so that vim changes the indent option just for fetch.

**Comment by dylanaraps** [comment]
I'm on Windows atm so I'll update the changelog later.

**Comment by dylanaraps** [comment]
Thanks for the help! :)

**Comment by tudurom** [comment]
Why are you on windows? `∑(O_O；)`?

**Comment by dylanaraps** [comment]
I'm playing CS:GO. :)

**Comment by tudurom** [comment]
Well it seems you're using AMD! I have a friend which plays CS:GO on AMD with no problem...

That's off-topic.

**Comment by dylanaraps** [comment]
The newest update has some performance issues, I was playing on linux full time before.

**Pull request merged**
